### ISSUE TITLE
Adding multiple domains/certificates to the SSL load balancer

### ISSUE THREAD

**Issue by igorkova** [gruntwork-io/terraform-google-static-assets#26]
Hi!

Great work as usual, just one question.

**Describe the solution you'd like**
Ability to add more than 1 domain/ssl certificate to the load balancer (HTTPS)

**Additional context**
Just wondering why is https://github.com/gruntwork-io/terraform-google-static-assets/blob/master/modules/http-load-balancer-website/main.tf#L30 and https://github.com/gruntwork-io/terraform-google-static-assets/blob/master/modules/http-load-balancer-website/main.tf#L35 taking single value and forwarding as a list when underlying module supports lists already. Why not simply taking a list on input and forwarding as-is?

**Comment by Etiene** [comment]
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by MoonMoon1919** [comment]
As per the message above, we will be closing this issue.
